package com.pismo.transaction.constants;

public interface ApiSpecConstants {

  String ACCOUNT_DESC = "APIs related to account functionality";
  String CREATE_ACCOUNT_DESC = "This API would create a account for a customer";
  String CREATE_ACCOUNT_SUMMARY = "Create Account";
  String RETRIEVE_ACCOUNT_DESC = "This API would retrieve account details for given account id";
  String RETRIEVE_ACCOUNT_SUMMARY = "Retrieve Account";
  String TRANSACTION_DESC = "API related to transaction functionality";
  String CREATE_TRANSACTION_DESC = "This API would create a transaction for a account with given operation id";
  String CREATE_TRANSACTION_SUMMARY = "Create transaction";

  String DOCUMENT_ID = "Document number of the customer";

  String NAME = "Name of the customer";

  String ACCOUNT_ID = "Account id of the customer created";

  String ACCOUNT_ID_RETRIEVE = "Account id of the customer to retrieve";

  String TXN_AMOUNT = "Transaction amount";

  String EXT_TXN_ID = "External txn should be an unique id for each txn";

  String INT_TXN_ID = "Transaction ref id generated by the system for each txn";

  String TXN_DESC = "Operation type description";

  String TXNTYPE = "Transaction type of transaction";

  String OPERATION_ID = "Operation id of the transaction. As of now the allowed ids are 1: Normal Purchase, 2: Purchase with installments, 3: Withdrawal, 4: Credit Voucher";

  String ERROR_CODE = "Error code";

  String ERROR_MESSAGE = "Error message";

  String VALIDATION_ERRORS = "List of validation error in case of bad request";
}
